basic/controllers/CacheController.php
<?php
/**
 * Eugine Terentev <eugine@terentev.net>
 */

namespace app\controllers;

use app\components\BackendController;
use Yii;
use yii\caching\Cache;
use yii\caching\TagDependency;
use yii\data\ArrayDataProvider;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\HttpException;

/**
 * Class CacheController
 * @package backend\controllers
 */
class CacheController extends BackendController
{
    /**
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ArrayDataProvider(['allModels'=>$this->findCaches()]);
        return $this->render('index', ['dataProvider'=>$dataProvider]);
    }

    /**
     * @param $id
     * @return \yii\web\Response
     * @throws HttpException
     */
    public function actionFlushCache($id)
    {
        if($this->getCache($id)->flush()){
            Yii::$app->session->setFlash('alert', [
                'body'=>'Cache has been successfully flushed',
                'options'=>['class'=>'alert-success']
            ]);
        };
        return $this->redirect(['index']);
    }

    /**
     * @param $id
     * @param $key
     * @return \yii\web\Response
     * @throws HttpException
     */
    public function actionFlushCacheKey($id, $key)
    {
        if($this->getCache($id)->delete($key)){
            Yii::$app->session->setFlash('alert', [
                'body'=>'Cache entry has been successfully deleted',
                'options'=>['class'=>'alert-success']
            ]);
        };
        return $this->redirect(['index']);
    }

    /**
     * @param $id
     * @param $tag
     * @return \yii\web\Response
     * @throws HttpException
     */
    public function actionFlushCacheTag($id, $tag)
    {
        TagDependency::invalidate($this->getCache($id), $tag);
        Yii::$app->session->setFlash('alert', [
            'body'=>'TagDependency was invalidated',
            'options'=>['class'=>'alert-success']
        ]);
        return $this->redirect(['index']);
    }

    /**
     * @param $id
     * @return \yii\caching\Cache|null
     * @throws HttpException
     * @throws \yii\base\InvalidConfigException
     */
    protected function getCache($id)
    {
        if(!in_array($id, array_keys($this->findCaches()))){
            throw new HttpException(400, 'Given cache name is not a name of cache component');
        }
        return Yii::$app->get($id);
    }

    /**
     * Returns array of caches in the system, keys are cache components names, values are class names.
     * @param array $cachesNames caches to be found
     * @return array
     */
    private function findCaches(array $cachesNames = [])
    {
        $caches = [];
        $components = Yii::$app->getComponents();
        $findAll = ($cachesNames == []);

        foreach ($components as $name => $component) {
            if (!$findAll && !in_array($name, $cachesNames)) {
                continue;
            }

            if ($component instanceof Cache) {
                $caches[$name] = ['name'=>$name, 'class'=>get_class($component)];
            } elseif (is_array($component) && isset($component['class']) && $this->isCacheClass($component['class'])) {
                $caches[$name] = ['name'=>$name, 'class'=>$component['class']];
            } elseif (is_string($component) && $this->isCacheClass($component)) {
                $caches[$name] = ['name'=>$name, 'class'=>$component];
            }
        }

        return $caches;
    }

    /**
     * Checks if given class is a Cache class.
     * @param string $className class name.
     * @return boolean
     */
    private function isCacheClass($className)
    {
        return is_subclass_of($className, Cache::className());
    }

}

basic/controllers/LogController.php
<?php

namespace app\controllers;

use app\components\BackendController;
use Yii;
use app\models\SystemLog;
use app\models\SystemLogSearch;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * LogController implements the CRUD actions for SystemLog model.
 */
class LogController extends BackendController
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'clear' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all SystemLog models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SystemLogSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        if(strcasecmp(Yii::$app->request->method, 'delete') == 0){
            SystemLog::deleteAll($dataProvider->query->where);
            return $this->refresh();
        }
        $dataProvider->sort = [
            'defaultOrder'=>['log_time'=>SORT_DESC]
        ];

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single SystemLog model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Deletes an existing SystemLog model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the SystemLog model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return SystemLog the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = SystemLog::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

basic/controllers/SystemInformationController.php
<?php
/**
 * Author: Eugine Terentev <eugine@terentev.net>
 */

namespace app\controllers;

use app\components\BackendController;
use probe\Factory;
use yii\helpers\Html;
use yii\web\Controller;
use yii\web\Response;
use Yii;

class SystemInformationController extends BackendController
{
    public function actionIndex()
    {
        $provider = Factory::create();
        if ($provider) {
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                if ($key = Yii::$app->request->get('data')) {
                    switch($key){
                        case 'cpu_usage':
                            return$provider->getCpuUsage();
                            break;
                        case 'memory_usage':
                            return ($provider->getTotalMem() - $provider->getFreeMem()) / $provider->getTotalMem();
                            break;
                    }
                }
            } else {
                return $this->render('index', ['provider' => $provider]);
            }
        } else {
            return $this->render('fail');
        }
    }
}

basic/views/layouts/_base.php
<?php
use yii\helpers\Html;
use yii\helpers\ArrayHelper;

/* @var $this \yii\web\View */
/* @var $content string */

\app\assets\BackendAsset::register($this);

if(!Yii::$app->user->isGuest){
    \app\assets\AppAsset::register($this);
}

$this->params['body-class'] = array_key_exists('body-class', $this->params) ?
    $this->params['body-class']
    : null;
?>

<?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>

        <!--    <link href="css/morris/morris.css" rel="stylesheet" type="text/css" />
            <link href="css/jvectormap/jquery-jvectormap-1.2.2.css" rel="stylesheet" type="text/css" />
            <link href="css/fullcalendar/fullcalendar.css" rel="stylesheet" type="text/css" />
            <link href="css/daterangepicker/daterangepicker-bs3.css" rel="stylesheet" type="text/css" />-->


    </head>
    <body class="<?= ArrayHelper::getValue($this->params, 'body-class') ?> skin-blue">
    <?php $this->beginBody() ?>
    <?= $content ?>
    <?php $this->endBody() ?>
    </body>
    </html>
<?php $this->endPage() ?>

basic/views/layouts/main.php
<?php
/**
 * @var $this yii\web\View
 */
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\Breadcrumbs;

?>
<?php $this->beginContent('@app/views/layouts/_base.php'); ?>
    <!-- header logo: style can be found in header.less -->
    <header class="header">
        <a href="<?= Yii::$app->homeUrl ?>" class="logo">
            <!-- Add the class icon to your logo image or logo icon to add the margining -->
            <?= Yii::$app->name ?>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
            <!-- Sidebar toggle button-->
            <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only"><?= Yii::t('backend', 'Toggle navigation') ?></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <div class="navbar-right">
                <ul class="nav navbar-nav">

                    <!-- Notifications: style can be found in dropdown.less -->
                    <li id="log-dropdown" class="dropdown notifications-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-warning"></i>
                        <span class="badge bg-red">
                            <?= \app\models\SystemLog::find()->count() ?>
                        </span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header"><?= Yii::t('backend', 'You have {num} log items', ['num'=>\app\models\SystemLog::find()->count()]) ?></li>
                            <li>
                                <!-- inner menu: contains the actual data -->
                                <ul class="menu">
                                    <?php foreach(\app\models\SystemLog::find()->orderBy(['log_time'=>SORT_DESC])->limit(5)->all() as $logEntry): ?>
                                        <li>
                                            <a href="<?= Yii::$app->urlManager->createUrl(['/log/view', 'id'=>$logEntry->id]) ?>">
                                                <i class="fa fa-warning <?= $logEntry->level == \yii\log\Logger::LEVEL_ERROR ? 'bg-red' : 'bg-yellow' ?>"></i>
                                                <?= $logEntry->category ?>
                                            </a>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </li>
                            <li class="footer">
                                <?= Html::a(Yii::t('backend', 'View all'), ['/log/index']) ?>
                            </li>
                        </ul>
                    </li>
                    <!-- User Account: style can be found in dropdown.less -->
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="glyphicon glyphicon-user"></i>
                            <span>Admin<i class="caret"></i></span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header bg-light-blue">
                                <img src="/img/anonymous.png" class="img-circle" alt="User Image" />
                                <p>
                                    Admin
                                </p>
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-right">
                                    <?= Html::a(Yii::t('backend', 'Logout'), ['/site/logout'], ['class'=>'btn btn-default btn-flat', 'data-method' => 'post']) ?>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="wrapper row-offcanvas row-offcanvas-left">
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="left-side sidebar-offcanvas">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="/img/anonymous.png" class="img-circle" alt="User Image" />
                    </div>
                    <div class="pull-left info">
                        <p>Admin</p>
                        <a href="<?php echo \yii\helpers\Url::to(['/sign-in/profile']) ?>">
                            <i class="fa fa-circle text-success"></i>
                            <?= Yii::$app->formatter->asDatetime(time()) ?>
                        </a>
                    </div>
                </div>
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <?= app\components\widgets\Menu::widget([
                        'options'=>['class'=>'sidebar-menu'],
                        'labelTemplate' => '<a href="#">{icon}<span>{label}</span>{right-icon}{badge}</a>',
                        'linkTemplate' => '<a href="{url}">{icon}<span>{label}</span>{right-icon}{badge}</a>',
                        'submenuTemplate'=>"\n<ul class=\"treeview-menu\">\n{items}\n</ul>\n",
                        'activateParents'=>true,
                        'items'=>[

                            [
                                'label'=>'Пользователи',
                                'url'=>['/clients'],
                                'icon'=>'<i class="fa fa-life-ring"></i>',
                            ],
                            [
                                'label'=>'Вопросы',
                                'url'=>['/questions'],
                                'icon'=>'<i class="fa fa-life-ring"></i>',
                            ],
                            [
                                'label'=>'Ответы пользователей',
                                'url'=>['/user_data/answers/index'],
                                'icon'=>'<i class="fa fa-life-ring"></i>',
                            ],

//                            [
//                                'label'=>'Подготовка',
//                                'icon'=>'<i class="fa fa-bar-chart-o"></i>',
//                                'options'=>['class'=>'treeview'],
//                                'items'=>[
//                                    ['label'=>'Шаблон', 'url'=>['/background'], 'icon'=>'<i class="fa fa-angle-double-right"></i>'],
//                                    ['label'=>'Шрифт', 'url'=>['/fonts'], 'icon'=>'<i class="fa fa-angle-double-right"></i>'],
//                                    ['label'=>'Текст', 'url'=>['/text'], 'icon'=>'<i class="fa fa-angle-double-right"></i>'],
//                                    ['label'=>'Headers', 'url'=>['/elements'], 'icon'=>'<i class="fa fa-angle-double-right"></i>'],
//                                ]
//                            ],



                            [
                                'label'=>Yii::t('backend', 'System'),
                                'icon'=>'<i class="fa fa-cogs"></i>',
                                'options'=>['class'=>'treeview'],
                                'items'=>[
                                    ['label'=>Yii::t('backend', 'Cache'), 'url'=>['/cache/index'], 'icon'=>'<i class="fa fa-angle-double-right"></i>'],

                                    [
                                        'label'=>Yii::t('backend', 'System Information'),
                                        'url'=>['/system-information/index'],
                                        'icon'=>'<i class="fa fa-angle-double-right"></i>'
                                    ],
                                    [
                                        'label'=>Yii::t('backend', 'Logs'),
                                        'url'=>['/log/index'],
                                        'icon'=>'<i class="fa fa-angle-double-right"></i>',
                                        'badge'=>\app\models\SystemLog::find()->count(),
                                        'badgeBgClass'=>'bg-red',
                                    ],
                                ]
                            ]
                        ]
                    ]) ?>
            </section>
            <!-- /.sidebar -->
        </aside>

        <!-- Right side column. Contains the navbar and content of the page -->
        <aside class="right-side">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    <?= $this->title ?>
                    <?php if(isset($this->params['subtitle'])): ?>
                        <small><?= $this->params['subtitle'] ?></small>
                    <?php endif; ?>
                </h1>

                <?= Breadcrumbs::widget([
                        'tag'=>'ol',
                        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                    ]) ?>
            </section>

            <!-- Main content -->
            <section class="content">
                <?php if(Yii::$app->session->hasFlash('alert')):?>
                    <?= \yii\bootstrap\Alert::widget([
                            'body'=>ArrayHelper::getValue(Yii::$app->session->getFlash('alert'), 'body'),
                            'options'=>ArrayHelper::getValue(Yii::$app->session->getFlash('alert'), 'options'),
                        ])?>
                <?php endif; ?>
                <?= $content ?>
            </section><!-- /.content -->
        </aside><!-- /.right-side -->
    </div><!-- ./wrapper -->


    <?php
    yii\bootstrap\Modal::begin([
            'headerOptions' => ['id' => 'modalHeader'],
            'header'=>'<span id="modalHeaderContent"></span>',
            'id' => 'modalClient',
            'size' => 'modal-lg',
            //keeps from closing modal with esc key or by clicking out of the modal.
            // user must click cancel or X to close
            //'clientOptions' => ['backdrop' => 'static', 'keyboard' => FALSE],
            'closeButton' => [
                'label' => 'х',
                'class' => 'btn btn-danger btn-sm pull-right',
            ],
        ]);
    echo "<div id='modalContent'></div>";
    yii\bootstrap\Modal::end();
    ?>

<div id="loading">
    <img src="img/1.gif">
</div>

<?php $this->endContent(); ?>